### PR TITLE
update to edition 2018 and stable channel

### PR DESCRIPTION
**Pull request by longwusha**
update to edition 2018 and stable channel

### CODE REVIEW

**Comment by seppo0010** [comment]
Hi @longwusha. Could you fork `rust-skiplist`, push your changes and change it so it uses your git repository instead of a path?

**Comment by longwusha** [comment]
fork rust-skiplist will be a good idea, I will try it.

**Comment by seppo0010** [comment]
OK, I can wait for the fork or merge it as is, let me know what you prefer.

**Comment by longwusha** [comment]
I think wait for the fork is better. Just copy and upload the skiplist source code to this repo may have some LICENSE problem.

**Comment by longwusha** [comment]
@seppo0010  Everything is ready. If there is no other problem, I think we can merge it.

**Pull request merged**
